/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSupplementsRouteImport } from './routes/_authenticated/supplements'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedMealsRouteImport } from './routes/_authenticated/meals'
import { Route as AuthenticatedLogRouteImport } from './routes/_authenticated/log'
import { Route as AuthenticatedInsightsRouteImport } from './routes/_authenticated/insights'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedCommunityRouteImport } from './routes/_authenticated/community'
import { Route as AuthenticatedInsightsIndexRouteImport } from './routes/_authenticated/insights.index'
import { Route as AuthenticatedCommunityIndexRouteImport } from './routes/_authenticated/community.index'
import { Route as AuthenticatedInsightsBiologicalAgeRouteImport } from './routes/_authenticated/insights.biological-age'
import { Route as AuthenticatedCommunityGroupIdRouteImport } from './routes/_authenticated/community.$groupId'
import { Route as AuthenticatedCommunityJoinCodeRouteImport } from './routes/_authenticated/community.join.$code'
import { Route as AuthenticatedCommunityGroupIdSettingsRouteImport } from './routes/_authenticated/community.$groupId.settings'

const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupplementsRoute =
  AuthenticatedSupplementsRouteImport.update({
    id: '/supplements',
    path: '/supplements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMealsRoute = AuthenticatedMealsRouteImport.update({
  id: '/meals',
  path: '/meals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogRoute = AuthenticatedLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInsightsRoute = AuthenticatedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommunityRoute = AuthenticatedCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInsightsIndexRoute =
  AuthenticatedInsightsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedInsightsRoute,
  } as any)
const AuthenticatedCommunityIndexRoute =
  AuthenticatedCommunityIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCommunityRoute,
  } as any)
const AuthenticatedInsightsBiologicalAgeRoute =
  AuthenticatedInsightsBiologicalAgeRouteImport.update({
    id: '/biological-age',
    path: '/biological-age',
    getParentRoute: () => AuthenticatedInsightsRoute,
  } as any)
const AuthenticatedCommunityGroupIdRoute =
  AuthenticatedCommunityGroupIdRouteImport.update({
    id: '/$groupId',
    path: '/$groupId',
    getParentRoute: () => AuthenticatedCommunityRoute,
  } as any)
const AuthenticatedCommunityJoinCodeRoute =
  AuthenticatedCommunityJoinCodeRouteImport.update({
    id: '/join/$code',
    path: '/join/$code',
    getParentRoute: () => AuthenticatedCommunityRoute,
  } as any)
const AuthenticatedCommunityGroupIdSettingsRoute =
  AuthenticatedCommunityGroupIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedCommunityGroupIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/trust': typeof TrustRoute
  '/community': typeof AuthenticatedCommunityRouteWithChildren
  '/import': typeof AuthenticatedImportRoute
  '/insights': typeof AuthenticatedInsightsRouteWithChildren
  '/log': typeof AuthenticatedLogRoute
  '/meals': typeof AuthenticatedMealsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/supplements': typeof AuthenticatedSupplementsRoute
  '/community/$groupId': typeof AuthenticatedCommunityGroupIdRouteWithChildren
  '/insights/biological-age': typeof AuthenticatedInsightsBiologicalAgeRoute
  '/community/': typeof AuthenticatedCommunityIndexRoute
  '/insights/': typeof AuthenticatedInsightsIndexRoute
  '/community/$groupId/settings': typeof AuthenticatedCommunityGroupIdSettingsRoute
  '/community/join/$code': typeof AuthenticatedCommunityJoinCodeRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/trust': typeof TrustRoute
  '/import': typeof AuthenticatedImportRoute
  '/log': typeof AuthenticatedLogRoute
  '/meals': typeof AuthenticatedMealsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/supplements': typeof AuthenticatedSupplementsRoute
  '/': typeof AuthenticatedIndexRoute
  '/community/$groupId': typeof AuthenticatedCommunityGroupIdRouteWithChildren
  '/insights/biological-age': typeof AuthenticatedInsightsBiologicalAgeRoute
  '/community': typeof AuthenticatedCommunityIndexRoute
  '/insights': typeof AuthenticatedInsightsIndexRoute
  '/community/$groupId/settings': typeof AuthenticatedCommunityGroupIdSettingsRoute
  '/community/join/$code': typeof AuthenticatedCommunityJoinCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/trust': typeof TrustRoute
  '/_authenticated/community': typeof AuthenticatedCommunityRouteWithChildren
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/insights': typeof AuthenticatedInsightsRouteWithChildren
  '/_authenticated/log': typeof AuthenticatedLogRoute
  '/_authenticated/meals': typeof AuthenticatedMealsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/supplements': typeof AuthenticatedSupplementsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/community/$groupId': typeof AuthenticatedCommunityGroupIdRouteWithChildren
  '/_authenticated/insights/biological-age': typeof AuthenticatedInsightsBiologicalAgeRoute
  '/_authenticated/community/': typeof AuthenticatedCommunityIndexRoute
  '/_authenticated/insights/': typeof AuthenticatedInsightsIndexRoute
  '/_authenticated/community/$groupId/settings': typeof AuthenticatedCommunityGroupIdSettingsRoute
  '/_authenticated/community/join/$code': typeof AuthenticatedCommunityJoinCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/trust'
    | '/community'
    | '/import'
    | '/insights'
    | '/log'
    | '/meals'
    | '/settings'
    | '/supplements'
    | '/community/$groupId'
    | '/insights/biological-age'
    | '/community/'
    | '/insights/'
    | '/community/$groupId/settings'
    | '/community/join/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/reset-password'
    | '/trust'
    | '/import'
    | '/log'
    | '/meals'
    | '/settings'
    | '/supplements'
    | '/'
    | '/community/$groupId'
    | '/insights/biological-age'
    | '/community'
    | '/insights'
    | '/community/$groupId/settings'
    | '/community/join/$code'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/trust'
    | '/_authenticated/community'
    | '/_authenticated/import'
    | '/_authenticated/insights'
    | '/_authenticated/log'
    | '/_authenticated/meals'
    | '/_authenticated/settings'
    | '/_authenticated/supplements'
    | '/_authenticated/'
    | '/_authenticated/community/$groupId'
    | '/_authenticated/insights/biological-age'
    | '/_authenticated/community/'
    | '/_authenticated/insights/'
    | '/_authenticated/community/$groupId/settings'
    | '/_authenticated/community/join/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TrustRoute: typeof TrustRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supplements': {
      id: '/_authenticated/supplements'
      path: '/supplements'
      fullPath: '/supplements'
      preLoaderRoute: typeof AuthenticatedSupplementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meals': {
      id: '/_authenticated/meals'
      path: '/meals'
      fullPath: '/meals'
      preLoaderRoute: typeof AuthenticatedMealsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/log': {
      id: '/_authenticated/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof AuthenticatedLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insights': {
      id: '/_authenticated/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedInsightsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/community': {
      id: '/_authenticated/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AuthenticatedCommunityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insights/': {
      id: '/_authenticated/insights/'
      path: '/'
      fullPath: '/insights/'
      preLoaderRoute: typeof AuthenticatedInsightsIndexRouteImport
      parentRoute: typeof AuthenticatedInsightsRoute
    }
    '/_authenticated/community/': {
      id: '/_authenticated/community/'
      path: '/'
      fullPath: '/community/'
      preLoaderRoute: typeof AuthenticatedCommunityIndexRouteImport
      parentRoute: typeof AuthenticatedCommunityRoute
    }
    '/_authenticated/insights/biological-age': {
      id: '/_authenticated/insights/biological-age'
      path: '/biological-age'
      fullPath: '/insights/biological-age'
      preLoaderRoute: typeof AuthenticatedInsightsBiologicalAgeRouteImport
      parentRoute: typeof AuthenticatedInsightsRoute
    }
    '/_authenticated/community/$groupId': {
      id: '/_authenticated/community/$groupId'
      path: '/$groupId'
      fullPath: '/community/$groupId'
      preLoaderRoute: typeof AuthenticatedCommunityGroupIdRouteImport
      parentRoute: typeof AuthenticatedCommunityRoute
    }
    '/_authenticated/community/join/$code': {
      id: '/_authenticated/community/join/$code'
      path: '/join/$code'
      fullPath: '/community/join/$code'
      preLoaderRoute: typeof AuthenticatedCommunityJoinCodeRouteImport
      parentRoute: typeof AuthenticatedCommunityRoute
    }
    '/_authenticated/community/$groupId/settings': {
      id: '/_authenticated/community/$groupId/settings'
      path: '/settings'
      fullPath: '/community/$groupId/settings'
      preLoaderRoute: typeof AuthenticatedCommunityGroupIdSettingsRouteImport
      parentRoute: typeof AuthenticatedCommunityGroupIdRoute
    }
  }
}

interface AuthenticatedCommunityGroupIdRouteChildren {
  AuthenticatedCommunityGroupIdSettingsRoute: typeof AuthenticatedCommunityGroupIdSettingsRoute
}

const AuthenticatedCommunityGroupIdRouteChildren: AuthenticatedCommunityGroupIdRouteChildren =
  {
    AuthenticatedCommunityGroupIdSettingsRoute:
      AuthenticatedCommunityGroupIdSettingsRoute,
  }

const AuthenticatedCommunityGroupIdRouteWithChildren =
  AuthenticatedCommunityGroupIdRoute._addFileChildren(
    AuthenticatedCommunityGroupIdRouteChildren,
  )

interface AuthenticatedCommunityRouteChildren {
  AuthenticatedCommunityGroupIdRoute: typeof AuthenticatedCommunityGroupIdRouteWithChildren
  AuthenticatedCommunityIndexRoute: typeof AuthenticatedCommunityIndexRoute
  AuthenticatedCommunityJoinCodeRoute: typeof AuthenticatedCommunityJoinCodeRoute
}

const AuthenticatedCommunityRouteChildren: AuthenticatedCommunityRouteChildren =
  {
    AuthenticatedCommunityGroupIdRoute:
      AuthenticatedCommunityGroupIdRouteWithChildren,
    AuthenticatedCommunityIndexRoute: AuthenticatedCommunityIndexRoute,
    AuthenticatedCommunityJoinCodeRoute: AuthenticatedCommunityJoinCodeRoute,
  }

const AuthenticatedCommunityRouteWithChildren =
  AuthenticatedCommunityRoute._addFileChildren(
    AuthenticatedCommunityRouteChildren,
  )

interface AuthenticatedInsightsRouteChildren {
  AuthenticatedInsightsBiologicalAgeRoute: typeof AuthenticatedInsightsBiologicalAgeRoute
  AuthenticatedInsightsIndexRoute: typeof AuthenticatedInsightsIndexRoute
}

const AuthenticatedInsightsRouteChildren: AuthenticatedInsightsRouteChildren = {
  AuthenticatedInsightsBiologicalAgeRoute:
    AuthenticatedInsightsBiologicalAgeRoute,
  AuthenticatedInsightsIndexRoute: AuthenticatedInsightsIndexRoute,
}

const AuthenticatedInsightsRouteWithChildren =
  AuthenticatedInsightsRoute._addFileChildren(
    AuthenticatedInsightsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCommunityRoute: typeof AuthenticatedCommunityRouteWithChildren
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedInsightsRoute: typeof AuthenticatedInsightsRouteWithChildren
  AuthenticatedLogRoute: typeof AuthenticatedLogRoute
  AuthenticatedMealsRoute: typeof AuthenticatedMealsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSupplementsRoute: typeof AuthenticatedSupplementsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCommunityRoute: AuthenticatedCommunityRouteWithChildren,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedInsightsRoute: AuthenticatedInsightsRouteWithChildren,
  AuthenticatedLogRoute: AuthenticatedLogRoute,
  AuthenticatedMealsRoute: AuthenticatedMealsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSupplementsRoute: AuthenticatedSupplementsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TrustRoute: TrustRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
